name: app_filmes
description: App Filmes.
publish_to: 'none'
version: 2.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_core_platform_interface: ^5.2.0
  firebase_remote_config: ^5.0.4
  flutter:
    sdk: flutter
  flutter_rating_stars: ^1.1.0
  flutter_signin_button: ^2.0.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: FilmesAppIcons
      fonts:
        - asset: assets/fonts/FilmesAppIcons.ttf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-Semibold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
